// data.js
const dataset = [
    {
        noUrut: 10,
        nama: "YUNAN FARUK EFFENDI",
        dapil: 1,
        partai: "Nasdem",
        ranked: "LEGEND",
        jumlahSuara: 7771,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 5014,
        kekuatanDiBasis: "65%",
        statusDiPartai: "Transaksional",
        profileSummary: "Ex Lurah",
        status: "Hijau",
        pic: "BP3 & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/f/8/7/1683288379_bf0ca745-0bb5-45af-8520-5e7fe37af56b.webp"
    },
    {
        noUrut: 4,
        nama: "H. SAMSUL HADI, S.Ag.",
        dapil: 1,
        partai: "PKB",
        ranked: "LEGEND",
        jumlahSuara: 6491,
        jadiGagal: "Gagal",
        basisSuara: "Sedati",
        suaraDiBasis: 3214,
        kekuatanDiBasis: "50%",
        statusDiPartai: "Ideologis",
        profileSummary: "Ex aleg paw subandi",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/9/e/e/1688658560_358a2ccb-ad8d-4919-a3d7-ed4ddd844138.webp"
    },
    {
        noUrut: 10,
        nama: "TRI PRASTIYONO, S.H.",
        dapil: 1,
        partai: "PKB",
        ranked: "LEGEND",
        jumlahSuara: 5726,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 5446,
        kekuatanDiBasis: "95%",
        statusDiPartai: "Transaksional",
        profileSummary: "Ex Lurah",
        status: "Kuning",
        pic: "BP3 & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/5/7/3/1688662324_403283d9-316e-476f-9b77-086475074399.webp"
    },
    {
        noUrut: 2,
        nama: "ANDRI CHRYSTANTO, S.T., M.M.",
        dapil: 1,
        partai: "Gerindra",
        ranked: "LEGEND",
        jumlahSuara: 5457,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 4252,
        kekuatanDiBasis: "78%",
        statusDiPartai: "Ideologis",
        profileSummary: "Pengusaha",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/8/d/d/1683701216_4348a2f7-8aa7-40fb-8ed3-3910d1bb4402.webp"
    },
    {
        noUrut: 1,
        nama: "ARIEF BACHTIAR, S.T.",
        dapil: 1,
        partai: "Golkar",
        ranked: "EPIC",
        jumlahSuara: 4529,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 3406,
        kekuatanDiBasis: "75%",
        statusDiPartai: "Ideologis",
        profileSummary: "-",
        status: "Kuning",
        pic: "Fraksi & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/2/8/1683692338_26ef3c5f-a931-4726-b9ec-cd5770214637.webp"
    },
    {
        noUrut: 2,
        nama: "Hj. SYIFAUL UMMAH, S.Psi.",
        dapil: 1,
        partai: "PAN",
        ranked: "EPIC",
        jumlahSuara: 4187,
        jadiGagal: "Gagal",
        basisSuara: "Sedati",
        suaraDiBasis: 1971,
        kekuatanDiBasis: "47%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha Butik & Istri Pengusaha",
        status: "Hijau",
        pic: "BPKK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/7/f/b/1683088500_b8424424-857c-4840-ae23-bbbc9d6cae1a.webp"
    },
    {
        noUrut: 6,
        nama: "NUGROHO MARSISWANTO",
        dapil: 1,
        partai: "PKB",
        ranked: "EPIC",
        jumlahSuara: 4059,
        jadiGagal: "Gagal",
        basisSuara: "Sedati",
        suaraDiBasis: 2166,
        kekuatanDiBasis: "53%",
        statusDiPartai: "Ideologis",
        profileSummary: "Ketua Kantor Advokat",
        status: "Merah",
        pic: "BPH & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/0/1/1/1688659836_32c52489-0905-4d4f-b6b7-5a4c83c1fdf3.webp"
    },
    {
        noUrut: 1,
        nama: "MOCHAMMAD SOCHIB",
        dapil: 1,
        partai: "Nasdem",
        ranked: "EPIC",
        jumlahSuara: 3927,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 2744,
        kekuatanDiBasis: "70%",
        statusDiPartai: "Semi-Transaksional",
        profileSummary: "Ex Aleg",
        status: "Hijau",
        pic: "Fraksi & Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/64846/pas_foto/1683280198_2626950f-7e1c-472e-84bf-d36b3f348d73.jpeg"
    },
    {
        noUrut: 5,
        nama: "NOVA ERIN KISMIATI",
        dapil: 1,
        partai: "PKB",
        ranked: "EPIC",
        jumlahSuara: 3914,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 2548,
        kekuatanDiBasis: "65%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha Advertising",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/8/d/2/1688659375_d73a4e22-daa1-48c6-ba25-dd95228ff6c9.webp"
    },
    {
        noUrut: 7,
        nama: "PRADITYA A., S.E.",
        dapil: 1,
        partai: "PDIP",
        ranked: "EPIC",
        jumlahSuara: 3719,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 2187,
        kekuatanDiBasis: "59%",
        statusDiPartai: "Ideologis",
        profileSummary: "Anak Ex Bupati",
        status: "Hijau",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/4/b/6/1683703514_d309bd1e-e0d4-4875-ba44-9f0568d21b02.webp"
    },
    {
        noUrut: 3,
        nama: "NURUL AHDI, M.Si., M.H.",
        dapil: 1,
        partai: "PAN",
        ranked: "EPIC",
        jumlahSuara: 3320,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 1950,
        kekuatanDiBasis: "59%",
        statusDiPartai: "Transaksional",
        profileSummary: "Advokat",
        status: "Hijau",
        pic: "Pak NK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/d/4/a/1683089362_15e33a96-27fe-4039-a08b-2f4891020fae.webp"
    },
    {
        noUrut: 4,
        nama: "Dr. ABDUL SALAM, S.H., M.H.",
        dapil: 1,
        partai: "Golkar",
        ranked: "EPIC",
        jumlahSuara: 3311,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 1872,
        kekuatanDiBasis: "57%",
        statusDiPartai: "Ideologis",
        profileSummary: "Advokat",
        status: "Kuning",
        pic: "Pak NK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/b/7/3/1683711790_ef98117f-cd94-4571-9efb-d14af6c1f8b4.webp"
    },
    {
        noUrut: 2,
        nama: "SOEKARNO DEWA SAPUTRA",
        dapil: 1,
        partai: "PDIP",
        ranked: "RARE",
        jumlahSuara: 2859,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 1745,
        kekuatanDiBasis: "61%",
        statusDiPartai: "Ideologis",
        profileSummary: "Anak Ketua DPC PDIP",
        status: "Merah",
        pic: "BPH & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/d/c/d/1683703132_a5949678-37b9-41c4-8aa3-add99b5879f7.webp"
    },
    {
        noUrut: 5,
        nama: "dr. YUDY HERRYANTORO, M.M.",
        dapil: 1,
        partai: "PDIP",
        ranked: "RARE",
        jumlahSuara: 2748,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 1383,
        kekuatanDiBasis: "50%",
        statusDiPartai: "Transaksional",
        profileSummary: "Dokter Umum",
        status: "Hijau",
        pic: "Pak Deny & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/b/8/c/1696230680_72a3b069-6f7e-44bf-9273-236f801e74d1.webp"
    },
    {
        noUrut: 2,
        nama: "REVINDIA CARINA, S.I.Kom., M.I.Kom.",
        dapil: 1,
        partai: "Demokrat",
        ranked: "RARE",
        jumlahSuara: 2577,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 1783,
        kekuatanDiBasis: "69%",
        statusDiPartai: "Transaksional",
        profileSummary: "Selebgram & Duta Tourism",
        status: "Hijau",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/e/a/5/1691672958_0275aeb6-2a66-4cc3-81f6-211d6deb23e8.webp"
    },
    {
        noUrut: 3,
        nama: "Rr. IRA DAMAYANTI, S.H., M.Si.",
        dapil: 1,
        partai: "Gerindra",
        ranked: "RARE",
        jumlahSuara: 2481,
        jadiGagal: "Gagal",
        basisSuara: "Sidoarjo",
        suaraDiBasis: 861,
        kekuatanDiBasis: "35%",
        statusDiPartai: "Ideologis",
        profileSummary: "Wakil Ketua DPC Gerindra",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/6/1/7/1683008001_6ab1b2a8-5487-4b35-a1b8-ac1f03ccf2d0.webp"
    },
    {
        noUrut: 4,
        nama: "ABD. MUGHIS",
        dapil: 1,
        partai: "Gerindra",
        ranked: "RARE",
        jumlahSuara: 2085,
        jadiGagal: "Gagal",
        basisSuara: "Buduran",
        suaraDiBasis: 862,
        kekuatanDiBasis: "41%",
        statusDiPartai: "?",
        profileSummary: "Ketua KarTar Kab. Sidoarjo",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/4/a/4/1683548096_07a6c330-5d40-4dab-b9e6-c90d5e04c575.webp"
    },
    {
        noUrut: 4,
        nama: "HAMZAH PURWANDOYO, S.E.",
        dapil: 2,
        partai: "PKB",
        ranked: "LEGEND",
        jumlahSuara: 7500,
        jadiGagal: "Gagal",
        basisSuara: "Candi",
        suaraDiBasis: 3263,
        kekuatanDiBasis: "44%",
        statusDiPartai: "Transaksional",
        profileSummary: "Ex Aleg",
        status: "Hijau",
        pic: "P Deny & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/3/5/2/3515061507750002.webp"
    },
    {
        noUrut: 1,
        nama: "ABDUR ROHMAN FALAHI, S.H., M.H.I",
        dapil: 2,
        partai: "Nasdem",
        ranked: "LEGEND",
        jumlahSuara: 6884,
        jadiGagal: "Gagal",
        basisSuara: "Candi",
        suaraDiBasis: 5233,
        kekuatanDiBasis: "76%",
        statusDiPartai: "Transaksional",
        profileSummary: "Katib Syuriah Kec. Candi",
        status: "Kuning",
        pic: "BPU & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/4/8/1683632360_904e8acd-d7a2-43bb-9ce0-cfe22adedaf9.webp"
    },
    {
        noUrut: 1,
        nama: "H. SOLIKAN",
        dapil: 2,
        partai: "PPP",
        ranked: "LEGEND",
        jumlahSuara: 6774,
        jadiGagal: "Gagal",
        basisSuara: "Jabon",
        suaraDiBasis: 1881,
        kekuatanDiBasis: "28%",
        statusDiPartai: "Ideologis",
        profileSummary: "Ketua DPC PPP",
        status: "Kuning",
        pic: "P Deny & Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/485006/pas_foto/1696222535_5b2af0ef-5949-48ef-81b8-77c5e9e4c5c0.jpeg"
    },
    {
        noUrut: 2,
        nama: "MOH SIROJUDDIN, S.Sos.I.",
        dapil: 2,
        partai: "Demokrat",
        ranked: "LEGEND",
        jumlahSuara: 6244,
        jadiGagal: "Gagal",
        basisSuara: "Candi",
        suaraDiBasis: 4193,
        kekuatanDiBasis: "67%",
        statusDiPartai: "Transaksional",
        profileSummary: "Komunitas Balapan",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/b/c/e/1683816818_56b9623b-34a4-47e3-9add-0884a59e6318.webp"
    },
    {
        noUrut: 3,
        nama: "ACHMAD HADI YANTO, S.Pd.I.",
        dapil: 2,
        partai: "PDIP",
        ranked: "LEGEND",
        jumlahSuara: 6200,
        jadiGagal: "Gagal",
        basisSuara: "Candi",
        suaraDiBasis: 1672,
        kekuatanDiBasis: "27%",
        statusDiPartai: "Ideologis",
        profileSummary: "Pengusaha",
        status: "Kuning",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/7/d/d/1683702368_46952481-74ee-4094-98ad-ff3fc39f72c2.webp"
    },
    {
        noUrut: 5,
        nama: "Drs. H. KHOIRUL ANAM",
        dapil: 2,
        partai: "PKB",
        ranked: "LEGEND",
        jumlahSuara: 5299,
        jadiGagal: "Gagal",
        basisSuara: "Tanggulangin",
        suaraDiBasis: 2785,
        kekuatanDiBasis: "53%",
        statusDiPartai: "Ideologis",
        profileSummary: "Ex Aleg PKB 1999",
        status: "Merah",
        pic: "BPH & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/e/0/b/1696238466_9deb1db5-cc9a-4205-b7dd-63fba50f2dd8.webp"
    },
    {
        noUrut: 9,
        nama: "DEDY RACHMADANY SETIAWAN, S.T",
        dapil: 2,
        partai: "PDIP",
        ranked: "EPIC",
        jumlahSuara: 4756,
        jadiGagal: "Gagal",
        basisSuara: "Jabon",
        suaraDiBasis: 2473,
        kekuatanDiBasis: "52%",
        statusDiPartai: "Transaksional",
        profileSummary: "?",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/3/7/1683702408_7c6c3d89-2134-45c5-a766-c3e8afd4e763.webp"
    },
    {
        noUrut: 4,
        nama: "YUDI IMRON",
        dapil: 2,
        partai: "PDIP",
        ranked: "EPIC",
        jumlahSuara: 3759,
        jadiGagal: "Gagal",
        basisSuara: "Porong",
        suaraDiBasis: 2373,
        kekuatanDiBasis: "63%",
        statusDiPartai: "Transaksional",
        profileSummary: "Mantan Calon Kades",
        status: "Hijau",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/7/5/d/1683702252_91523556-ddef-4295-add4-080a144648ad.webp"
    },
    {
        noUrut: 2,
        nama: "MACHMUDATUL FATCHIYAH, S.H",
        dapil: 2,
        partai: "PKB",
        ranked: "EPIC",
        jumlahSuara: 3476,
        jadiGagal: "Gagal",
        basisSuara: "Porong",
        suaraDiBasis: 1639,
        kekuatanDiBasis: "47%",
        statusDiPartai: "Ideologis",
        profileSummary: "Ketua DPC Wanita PKB",
        status: "Merah",
        pic: "BPKK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/3/5/2/3515045709680002.webp"
    },
    {
        noUrut: 2,
        nama: "ZADIT TAQWA, M.IP.",
        dapil: 2,
        partai: "PAN",
        ranked: "EPIC",
        jumlahSuara: 3470,
        jadiGagal: "Gagal",
        basisSuara: "Tanggulangin",
        suaraDiBasis: 1417,
        kekuatanDiBasis: "41%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha",
        status: "Kuning",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/f/2/a/1683519843_d2bc912a-df5c-40b4-9eda-6e500df6191b.webp"
    },
    {
        noUrut: 1,
        nama: "dr. RACHMAD WALUJO",
        dapil: 2,
        partai: "PKS",
        ranked: "RARE",
        jumlahSuara: 2279,
        jadiGagal: "Gagal",
        basisSuara: "Porong",
        suaraDiBasis: 1228,
        kekuatanDiBasis: "54%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 8,
        nama: "ESPI SIMANGUNSONG, S,E. M.Ak.",
        dapil: 2,
        partai: "Gerindra",
        ranked: "RARE",
        jumlahSuara: 2201,
        jadiGagal: "Gagal",
        basisSuara: "Jabon",
        suaraDiBasis: 808,
        kekuatanDiBasis: "37%",
        statusDiPartai: "Ideologis",
        profileSummary: "Srikandi BHS",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/4/9/0/1683088892_9a66e240-81a6-4f10-8c03-d6cce2b5381a.webp"
    },
    {
        noUrut: 9,
        nama: "H. IBRAHIM WAHYU WINALUWIH",
        dapil: 2,
        partai: "Gerindra",
        ranked: "RARE",
        jumlahSuara: 2072,
        jadiGagal: "Gagal",
        basisSuara: "Porong",
        suaraDiBasis: 845,
        kekuatanDiBasis: "41%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/b/0/1683688449_0d82af29-b640-4354-a4ed-66ffa72ee886.webp"
    },
    {
        noUrut: 6,
        nama: "MARSONO",
        dapil: 2,
        partai: "Gerindra",
        ranked: "RARE",
        jumlahSuara: 2039,
        jadiGagal: "Gagal",
        basisSuara: "Candi",
        suaraDiBasis: 1599,
        kekuatanDiBasis: "78%",
        statusDiPartai: "Transaksional",
        profileSummary: "?",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/4/8/3/1683685005_35c38087-08c1-4945-8add-2b7cc90bff9e.webp"
    },
    {
        noUrut: 4,
        nama: "IZZUDIN KAHFI",
        dapil: 2,
        partai: "Gerindra",
        ranked: "RARE",
        jumlahSuara: 2022,
        jadiGagal: "Gagal",
        basisSuara: "Candi",
        suaraDiBasis: 1477,
        kekuatanDiBasis: "73%",
        statusDiPartai: "Ideologis",
        profileSummary: "Pengusaha",
        status: "Merah",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/9/e/0/1683789106_88fe764a-253b-4732-b6c7-23c7d4323fbe.webp"
    },
    {
        noUrut: 2,
        nama: "ABD. ROHMAN, S.H., M.Kn.",
        dapil: 2,
        partai: "PKS",
        ranked: "COMMON",
        jumlahSuara: 1882,
        jadiGagal: "Gagal",
        basisSuara: "Candi",
        suaraDiBasis: 835,
        kekuatanDiBasis: "44%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 2,
        nama: "JASMURI, S.Kom",
        dapil: 2,
        partai: "Nasdem",
        ranked: "COMMON",
        jumlahSuara: 1214,
        jadiGagal: "Gagal",
        basisSuara: "Tanggulangin",
        suaraDiBasis: 698,
        kekuatanDiBasis: "57%",
        statusDiPartai: "Transaksional",
        profileSummary: "Juragan Peternakan",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/7/1/e/1683291973_c4e671fc-1caf-482a-8b24-d1e2fd4d2b00.webp"
    },
    {
        noUrut: 5,
        nama: "HARMAN PRATOMO, S.T.",
        dapil: 3,
        partai: "PDIP",
        ranked: "LEGEND",
        jumlahSuara: 9531,
        jadiGagal: "Gagal",
        basisSuara: "Wonoayu",
        suaraDiBasis: 6292,
        kekuatanDiBasis: "66%",
        statusDiPartai: "Ideologis",
        profileSummary: "Wakil Ketua PAC Wonoayu",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/187571/pas_foto/1683692378_4cffc7a3-7c99-47e6-b8c4-a62234806568.jpeg"
    },
    {
        noUrut: 8,
        nama: "drg. H. ANANG SUHARI",
        dapil: 3,
        partai: "PKB",
        ranked: "LEGEND",
        jumlahSuara: 8542,
        jadiGagal: "Gagal",
        basisSuara: "Tulangan",
        suaraDiBasis: 4352,
        kekuatanDiBasis: "51%",
        statusDiPartai: "Transaksional",
        profileSummary: "Dokter gigi, ex napi koruptor, ex kades",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/d/e/f/1696140116_7d1da644-ced3-435f-af52-78c6933d3870.webp"
    },
    {
        noUrut: 4,
        nama: "ENDIK EKO PRAMONO, S.T.",
        dapil: 3,
        partai: "PDIP",
        ranked: "LEGEND",
        jumlahSuara: 6992,
        jadiGagal: "Gagal",
        basisSuara: "Krembung",
        suaraDiBasis: 5997,
        kekuatanDiBasis: "86%",
        statusDiPartai: "Ideologis",
        profileSummary: "Ex sekt PAC PDIP Krembung",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/9/6/2/1683692598_3c5b87e2-634f-4eb0-a69d-0db1010506e1.webp"
    },
    {
        noUrut: 1,
        nama: "ADIT HANANTA UTAMA, S.I.Kom.",
        dapil: 3,
        partai: "Demokrat",
        ranked: "LEGEND",
        jumlahSuara: 5179,
        jadiGagal: "Gagal",
        basisSuara: "Tulangan",
        suaraDiBasis: 2407,
        kekuatanDiBasis: "46%",
        statusDiPartai: "Ideologis",
        profileSummary: "PDP Muhamaddiyah",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/7/6/3/1683816734_d1d01564-37c8-402d-9c91-a59e58453ecb.webp"
    },
    {
        noUrut: 2,
        nama: "RIDUWAN, S.Sos.",
        dapil: 3,
        partai: "PDIP",
        ranked: "EPIC",
        jumlahSuara: 3879,
        jadiGagal: "Gagal",
        basisSuara: "Tulangan",
        suaraDiBasis: 2952,
        kekuatanDiBasis: "76%",
        statusDiPartai: "Ideologis",
        profileSummary: "Kabid PDIP",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/0/7/2/1683692175_ae2ceba9-2ef2-44e8-9c80-9eaee5a7cf7c.webp"
    },
    {
        noUrut: 8,
        nama: "ANANG MA'RUF, S.Pd.",
        dapil: 3,
        partai: "PKS",
        ranked: "EPIC",
        jumlahSuara: 3046,
        jadiGagal: "Gagal",
        basisSuara: "Prambon",
        suaraDiBasis: 1215,
        kekuatanDiBasis: "40%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 2,
        nama: "MOCHAMAD YANTO",
        dapil: 3,
        partai: "Gerindra",
        ranked: "RARE",
        jumlahSuara: 2707,
        jadiGagal: "Gagal",
        basisSuara: "Prambon",
        suaraDiBasis: 1251,
        kekuatanDiBasis: "46%",
        statusDiPartai: "Ideologis",
        profileSummary: "Kader Gerindra",
        status: "Kuning",
        pic: "BP3 & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/c/0/3/1683090046_f0541938-83e9-482f-bf8d-dde0d2ab38f7.webp"
    },
    {
        noUrut: 1,
        nama: "H. HENDRA WAHYUANA SUKOCO",
        dapil: 3,
        partai: "PKS",
        ranked: "RARE",
        jumlahSuara: 2522,
        jadiGagal: "Gagal",
        basisSuara: "Wonoayu",
        suaraDiBasis: 1672,
        kekuatanDiBasis: "66%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 4,
        nama: "IVAN DWI DARMAWAN",
        dapil: 3,
        partai: "Gerindra",
        ranked: "COMMON",
        jumlahSuara: 1680,
        jadiGagal: "Gagal",
        basisSuara: "Tulangan",
        suaraDiBasis: 491,
        kekuatanDiBasis: "29%",
        statusDiPartai: "Ideologis",
        profileSummary: "Anggota PC TIDAR",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/2/4/1683084121_3d524f2d-18bc-4e67-8d64-e0767b3031fb.webp"
    },
    {
        noUrut: 3,
        nama: "Hj. IDA PURWANTI, S.E",
        dapil: 3,
        partai: "PKB",
        ranked: "COMMON",
        jumlahSuara: 1484,
        jadiGagal: "Gagal",
        basisSuara: "Prambon",
        suaraDiBasis: 659,
        kekuatanDiBasis: "44%",
        statusDiPartai: "Ideologis",
        profileSummary: "anggota perempuan bangsa PKB",
        status: "Kuning",
        pic: "BPKK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/e/4/e/1688670109_56226a36-7059-4cc2-bec2-d328319a2aee.webp"
    },
    {
        noUrut: 1,
        nama: "MACHMUD, S.E., M.M.",
        dapil: 3,
        partai: "PAN",
        ranked: "COMMON",
        jumlahSuara: 1469,
        jadiGagal: "Gagal",
        basisSuara: "Wonoayu",
        suaraDiBasis: 634,
        kekuatanDiBasis: "43%",
        statusDiPartai: "Ideologis",
        profileSummary: "Mantan aleg PAN",
        status: "Kuning",
        pic: "BPH & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/7/3/1/1683520809_0c180a65-2c65-4603-9d35-abe363c0c52d.webp"
    },
    {
        noUrut: 2,
        nama: "WIDYA PURNOMO, S.E",
        dapil: 3,
        partai: "Demokrat",
        ranked: "COMMON",
        jumlahSuara: 1185,
        jadiGagal: "Gagal",
        basisSuara: "Krembung",
        suaraDiBasis: 570,
        kekuatanDiBasis: "48%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/7/b/7/1683817052_2447e974-4979-42ca-9884-f5174fa694a5.webp"
    },
    {
        noUrut: 1,
        nama: "I WAYAN BUDI BRAHMANA",
        dapil: 3,
        partai: "PSI",
        ranked: "COMMON",
        jumlahSuara: 1138,
        jadiGagal: "Gagal",
        basisSuara: "Tulangan",
        suaraDiBasis: 392,
        kekuatanDiBasis: "34%",
        statusDiPartai: "Transaksional",
        profileSummary: "Ketua DPW Pelita Prabu",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/d/0/6/1683705162_b7d65cb5-ed71-423b-ae51-35f34eb012a1.webp"
    },
    {
        noUrut: 4,
        nama: "ISWAHYUDI",
        dapil: 3,
        partai: "PKB",
        ranked: "COMMON",
        jumlahSuara: 1029,
        jadiGagal: "Gagal",
        basisSuara: "Prambon",
        suaraDiBasis: 528,
        kekuatanDiBasis: "51%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/1/f/1688668836_99c4cc4e-6bb1-449f-8dc9-d13733b5c830.webp"
    },
    {
        noUrut: 3,
        nama: "SUTIYOWATI, S.Sos.",
        dapil: 4,
        partai: "PKB",
        ranked: "LEGEND",
        jumlahSuara: 6637,
        jadiGagal: "Gagal",
        basisSuara: "Balongbendo",
        suaraDiBasis: 3791,
        kekuatanDiBasis: "57%",
        statusDiPartai: "Transaksional",
        profileSummary: "Juragan dan Ex Aleg",
        status: "Hijau",
        pic: "BPH & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/b/6/f/3515126004770004.webp"
    },
    {
        noUrut: 2,
        nama: "AULIA ULFA MAWARDHIKA",
        dapil: 4,
        partai: "Golkar",
        ranked: "LEGEND",
        jumlahSuara: 5975,
        jadiGagal: "Gagal",
        basisSuara: "Krian",
        suaraDiBasis: 3222,
        kekuatanDiBasis: "54%",
        statusDiPartai: "Ideologis",
        profileSummary: "Jurnalis, news anchor and kader golkar",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/8/e/1/1688378364_d27c296b-9b2b-40cc-b20f-a644326a0631.webp"
    },
    {
        noUrut: 3,
        nama: "KUSUMO ADI NUGROHO, S.E.",
        dapil: 4,
        partai: "PDIP",
        ranked: "LEGEND",
        jumlahSuara: 5158,
        jadiGagal: "Gagal",
        basisSuara: "Krian",
        suaraDiBasis: 2232,
        kekuatanDiBasis: "43%",
        statusDiPartai: "Ideologis",
        profileSummary: "Saudara Ex Kapolresta Sidoarjo",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/1/a/4/1683693470_32d242e9-a692-4a83-9bcb-e1ff9f596626.webp"
    },
    {
        noUrut: 1,
        nama: "BIMA ADE WIYATNO, S.H.",
        dapil: 4,
        partai: "Demokrat",
        ranked: "LEGEND",
        jumlahSuara: 5154,
        jadiGagal: "Gagal",
        basisSuara: "Krian",
        suaraDiBasis: 2143,
        kekuatanDiBasis: "42%",
        statusDiPartai: "Transaksional",
        profileSummary: "Lawyer",
        status: "Hijau",
        pic: "Pak NK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/6/3/1683819014_65036942-c9f8-4893-910e-d726ab5677ed.webp"
    },
    {
        noUrut: 4,
        nama: "H. SISWADJI ABIDIN, S.Sos, M.Si.",
        dapil: 4,
        partai: "PKB",
        ranked: "EPIC",
        jumlahSuara: 4912,
        jadiGagal: "Gagal",
        basisSuara: "Krian",
        suaraDiBasis: 3989,
        kekuatanDiBasis: "81%",
        statusDiPartai: "Transaksional",
        profileSummary: "Ex Sekwan",
        status: "Kuning",
        pic: "BPH & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/8/7/f/1688667771_f732c635-f3a4-44b9-b322-cdf5814d903a.webp"
    },
    {
        noUrut: 7,
        nama: "H. MOH. HERU SULTHON",
        dapil: 4,
        partai: "PKS",
        ranked: "RARE",
        jumlahSuara: 2190,
        jadiGagal: "Gagal",
        basisSuara: "Balongbendo",
        suaraDiBasis: 1738,
        kekuatanDiBasis: "79%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 2,
        nama: "MOCHAMAD BAHRUL MUSTOFA IDHOM, S.Pd.I.",
        dapil: 4,
        partai: "PKB",
        ranked: "RARE",
        jumlahSuara: 2184,
        jadiGagal: "Gagal",
        basisSuara: "Tarik",
        suaraDiBasis: 1232,
        kekuatanDiBasis: "56%",
        statusDiPartai: "Ideologis",
        profileSummary: "Ex aleg, Kader PKB",
        status: "Kuning",
        pic: "BPH & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/f/8/c/1688666900_27226c54-9735-4d7a-a664-501bc0691a82.webp"
    },
    {
        noUrut: 2,
        nama: "LELIYANA, S.E.",
        dapil: 4,
        partai: "PAN",
        ranked: "COMMON",
        jumlahSuara: 1969,
        jadiGagal: "Gagal",
        basisSuara: "Balongbendo",
        suaraDiBasis: 895,
        kekuatanDiBasis: "45%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: ""
    },
    {
        noUrut: 2,
        nama: "LANGGENG, S.Pd.I.",
        dapil: 4,
        partai: "PKS",
        ranked: "COMMON",
        jumlahSuara: 1842,
        jadiGagal: "Gagal",
        basisSuara: "Balongbendo",
        suaraDiBasis: 1223,
        kekuatanDiBasis: "66%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 4,
        nama: "AMALUS SHOLEHA",
        dapil: 4,
        partai: "Gerindra",
        ranked: "COMMON",
        jumlahSuara: 1826,
        jadiGagal: "Gagal",
        basisSuara: "Krian",
        suaraDiBasis: 1252,
        kekuatanDiBasis: "69%",
        statusDiPartai: "Ideologis",
        profileSummary: "Anggota PC Tidar Gerindra",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/5/5/8/1687837065_2a6c8d06-610a-4512-818f-8913664e2c33.webp"
    },
    {
        noUrut: 1,
        nama: "SAMSOLEH",
        dapil: 4,
        partai: "PKS",
        ranked: "COMMON",
        jumlahSuara: 1807,
        jadiGagal: "Gagal",
        basisSuara: "Tarik",
        suaraDiBasis: 1040,
        kekuatanDiBasis: "58%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 2,
        nama: "KUNTI AMBARAWATI",
        dapil: 4,
        partai: "Demokrat",
        ranked: "COMMON",
        jumlahSuara: 1788,
        jadiGagal: "Gagal",
        basisSuara: "Balongbendo",
        suaraDiBasis: 795,
        kekuatanDiBasis: "44%",
        statusDiPartai: "?",
        profileSummary: "?",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: ""
    },
    {
        noUrut: 7,
        nama: "MUHAMAD TRI KISNOWO HADI, S.Pd.I.",
        dapil: 4,
        partai: "Gerindra",
        ranked: "COMMON",
        jumlahSuara: 1369,
        jadiGagal: "Gagal",
        basisSuara: "Balongbendo",
        suaraDiBasis: 540,
        kekuatanDiBasis: "39%",
        statusDiPartai: "Transaksional",
        profileSummary: "Sek KAHMI Sidoarjo",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/6/3/b/1683775984_284d7a69-6ee3-42f8-9029-7840838b06aa.webp"
    },
    {
        noUrut: 5,
        nama: "MUH NURHADI A. S.",
        dapil: 4,
        partai: "PKB",
        ranked: "COMMON",
        jumlahSuara: 1118,
        jadiGagal: "Gagal",
        basisSuara: "Balongbendo",
        suaraDiBasis: 933,
        kekuatanDiBasis: "83%",
        statusDiPartai: "?",
        profileSummary: "?",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: ""
    },
    {
        noUrut: 1,
        nama: "H. SUTRISWOKO, S.H., M.Si.",
        dapil: 4,
        partai: "PPP",
        ranked: "COMMON",
        jumlahSuara: 1079,
        jadiGagal: "Gagal",
        basisSuara: "Balongbendo",
        suaraDiBasis: 471,
        kekuatanDiBasis: "44%",
        statusDiPartai: "Transaksional",
        profileSummary: "Ex Kapolsek",
        status: "Kuning",
        pic: "BP3 & Tim Hunter",
        photo: ""
    },
    {
        noUrut: 2,
        nama: "YULI ISTATIK",
        dapil: 4,
        partai: "Gerindra",
        ranked: "COMMON",
        jumlahSuara: 1047,
        jadiGagal: "Gagal",
        basisSuara: "Krian",
        suaraDiBasis: 529,
        kekuatanDiBasis: "51%",
        statusDiPartai: "?",
        profileSummary: "?",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: ""
    },
    {
        noUrut: 4,
        nama: "H. SUKIMIN, S.E.",
        dapil: 5,
        partai: "PKB",
        ranked: "LEGEND",
        jumlahSuara: 7090,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 6693,
        kekuatanDiBasis: "94%",
        statusDiPartai: "Transaksional",
        profileSummary: "Ex Kades",
        status: "Kuning",
        pic: "Bu Vike & Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/129940/pas_foto/1688659969_3f93ff74-c41a-4bdd-b187-a84ba0b20323.jpeg"
    },
    {
        noUrut: 1,
        nama: "NUR AMBARIYAH, S.Ag.",
        dapil: 5,
        partai: "PKB",
        ranked: "LEGEND",
        jumlahSuara: 6113,
        jadiGagal: "Gagal",
        basisSuara: "Sukodono",
        suaraDiBasis: 4066,
        kekuatanDiBasis: "67%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha & KepSek TK",
        status: "Merah",
        pic: "BPKK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/e/c/6/1688658128_ee18975b-74c4-4b0b-b5ad-aa07970044e1.webp"
    },
    {
        noUrut: 1,
        nama: "SAMSUL HADI, S.E., M.M.",
        dapil: 5,
        partai: "PDIP",
        ranked: "LEGEND",
        jumlahSuara: 5551,
        jadiGagal: "Gagal",
        basisSuara: "Sukodono",
        suaraDiBasis: 3342,
        kekuatanDiBasis: "60%",
        statusDiPartai: "Ideologis",
        profileSummary: "Sekt DPC PDIP",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/d/1/b/1683688578_248a7f5f-e279-490b-bde2-26d0a8b79f4a.webp"
    },
    {
        noUrut: 4,
        nama: "Drs. ARIEF YULIANTO",
        dapil: 5,
        partai: "PDIP",
        ranked: "EPIC",
        jumlahSuara: 4587,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 4251,
        kekuatanDiBasis: "93%",
        statusDiPartai: "?",
        profileSummary: "?",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/2/1/8/1683690484_3a0c8099-a352-4883-a1d1-ba5e98bf2981.webp"
    },
    {
        noUrut: 2,
        nama: "Hj. UMI KHADDAH, S.Pd.I.",
        dapil: 5,
        partai: "PPP",
        ranked: "EPIC",
        jumlahSuara: 4359,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 2399,
        kekuatanDiBasis: "55%",
        statusDiPartai: "Transaksional",
        profileSummary: "Ex Aleg",
        status: "Kuning",
        pic: "Bu Vike & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/b/b/3/1683799501_c15c5174-6fe6-4209-87af-7449f4f6980f.webp"
    },
    {
        noUrut: 7,
        nama: "BEJO",
        dapil: 5,
        partai: "PKB",
        ranked: "EPIC",
        jumlahSuara: 4168,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 3463,
        kekuatanDiBasis: "83%",
        statusDiPartai: "Transaksional",
        profileSummary: "Relawan Syaikhul Islam",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/129941/pas_foto/1688662660_3e88bc3a-0af8-48f9-9b0f-b01bf1add227.jpeg"
    },
    {
        noUrut: 1,
        nama: "Ir. Hj. NURHENDRIYATI NINGSIH",
        dapil: 5,
        partai: "Nasdem",
        ranked: "EPIC",
        jumlahSuara: 4017,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 3615,
        kekuatanDiBasis: "90%",
        statusDiPartai: "Ideologis",
        profileSummary: "Ex Aleg & Ex Ketua DPD",
        status: "Kuning",
        pic: "P Deny & Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/82483/pas_foto/1683355611_8e6ea043-3473-49f7-ac25-5d80d32b2077.jpeg"
    },
    {
        noUrut: 8,
        nama: "ENDANG KRISTIYAWATI",
        dapil: 5,
        partai: "PDIP",
        ranked: "EPIC",
        jumlahSuara: 3176,
        jadiGagal: "Gagal",
        basisSuara: "Sukodono",
        suaraDiBasis: 1646,
        kekuatanDiBasis: "52%",
        statusDiPartai: "Ideologis",
        profileSummary: "Pengusaha",
        status: "Kuning",
        pic: "BPJE & Tim hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/7/a/8/1683695842_135624a4-e6dd-48ae-ad56-7ba50b3887d0.webp"
    },
    {
        noUrut: 1,
        nama: "MOCH RIFQI NUR AZIZI, S.M.",
        dapil: 5,
        partai: "Demokrat",
        ranked: "EPIC",
        jumlahSuara: 3141,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 2667,
        kekuatanDiBasis: "85%",
        statusDiPartai: "Ideologis",
        profileSummary: "wakil ketua DPC",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/0/6/5/1683820254_c41a8c45-4988-4a3e-bd0b-3b665509db87.webp"
    },
    {
        noUrut: 2,
        nama: "M. THORIQUL HUDA, M.Ap.",
        dapil: 5,
        partai: "Golkar",
        ranked: "EPIC",
        jumlahSuara: 3007,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 2372,
        kekuatanDiBasis: "79%",
        statusDiPartai: "Ideologis",
        profileSummary: "Ex Aleg",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/210758/pas_foto/1683714375_fc19159c-eedc-462f-a3ca-873ceba8e0ab.jpeg"
    },
    {
        noUrut: 1,
        nama: "ZAINUL MILAHI",
        dapil: 5,
        partai: "Golkar",
        ranked: "COMMON",
        jumlahSuara: 1632,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 1310,
        kekuatanDiBasis: "80%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha & Ketua IKA PMII sda",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/4/2/5/1683361045_cc98db50-cc1f-4d23-abf6-302338999604.webp"
    },
    {
        noUrut: 2,
        nama: "DIAN PAHLEVI, S.IP.",
        dapil: 5,
        partai: "PKS",
        ranked: "COMMON",
        jumlahSuara: 1615,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 1225,
        kekuatanDiBasis: "76%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 4,
        nama: "SHINTA MEGAWATI, A.Md.",
        dapil: 5,
        partai: "Gerindra",
        ranked: "COMMON",
        jumlahSuara: 1452,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 1017,
        kekuatanDiBasis: "70%",
        statusDiPartai: "Transaksional",
        profileSummary: "Ex PR hotel The Jayakarta",
        status: "Kuning",
        pic: "BPKK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/5/9/5/1683694654_3f33746e-2a14-46d8-a1dd-964fd1aaed1b.webp"
    },
    {
        noUrut: 3,
        nama: "SUGENG WIDODO, S.TP, M.M.",
        dapil: 5,
        partai: "PKS",
        ranked: "COMMON",
        jumlahSuara: 1418,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 744,
        kekuatanDiBasis: "52%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 2,
        nama: "DJATMOKO EDY SURYANTO, S.T.",
        dapil: 5,
        partai: "PAN",
        ranked: "COMMON",
        jumlahSuara: 1131,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 977,
        kekuatanDiBasis: "86%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pimp Yys Pend Dewi Sartika Sda",
        status: "Hijau",
        pic: "BPU & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/0/2/1683620655_566a35f3-24a5-467a-a68f-594925c4832e.webp"
    },
    {
        noUrut: 1,
        nama: "EULIS CAHYA TARBIYAH, S.Sos., M.A.",
        dapil: 5,
        partai: "PSI",
        ranked: "COMMON",
        jumlahSuara: 1064,
        jadiGagal: "Gagal",
        basisSuara: "Taman",
        suaraDiBasis: 653,
        kekuatanDiBasis: "61%",
        statusDiPartai: "ideologis",
        profileSummary: "Bendum DPD PSI",
        status: "Kuning",
        pic: "BPKK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/f/9/6/1683562516_981407bd-1707-476b-879d-bbf336a34d18.webp"
    },
    {
        noUrut: 8,
        nama: "MUHTADIN",
        dapil: 6,
        partai: "PKB",
        ranked: "LEGEND",
        jumlahSuara: 7058,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 4999,
        kekuatanDiBasis: "71%",
        statusDiPartai: "Transaksional",
        profileSummary: "?",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/129948/pas_foto/1688663646_1620aba5-0a2a-4862-9284-4a6cb4490cb7.jpeg"
    },
    {
        noUrut: 2,
        nama: "MOCH. HILMI NIZAR DEFRIANSYAH, S. Ked.",
        dapil: 6,
        partai: "PAN",
        ranked: "LEGEND",
        jumlahSuara: 5698,
        jadiGagal: "Gagal",
        basisSuara: "Gedangan",
        suaraDiBasis: 3577,
        kekuatanDiBasis: "63%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pemuda",
        status: "Hijau",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/4/8/1683520855_9e40b802-39e0-4f10-801b-da98e13f2b26.webp"
    },
    {
        noUrut: 6,
        nama: "AGUS SALIM, S.Sos.",
        dapil: 6,
        partai: "PAN",
        ranked: "LEGEND",
        jumlahSuara: 5679,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 3134,
        kekuatanDiBasis: "55%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/202022/pas_foto/1683661928_d6cf080f-cb77-4734-82c2-5bfd3d3ba0b7.jpeg"
    },
    {
        noUrut: 1,
        nama: "KURNIAWAN YUDA SUSANTO",
        dapil: 6,
        partai: "Golkar",
        ranked: "LEGEND",
        jumlahSuara: 5648,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 4409,
        kekuatanDiBasis: "78%",
        statusDiPartai: "Ideologis",
        profileSummary: "Wakil ketua DPD",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.goodkind.id/dct/berkas-silon/calon/213790/pas_foto/1683700625_7aac442a-580f-4d1a-b847-594c865118bb.jpeg"
    },
    {
        noUrut: 1,
        nama: "H. HARIS, S.Pi., M.Si.",
        dapil: 6,
        partai: "PAN",
        ranked: "LEGEND",
        jumlahSuara: 5225,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 3387,
        kekuatanDiBasis: "65%",
        statusDiPartai: "Ideologis",
        profileSummary: "Bendahara DPD",
        status: "Merah",
        pic: "P Deny & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/8/6/9/1683520759_ab0a4620-c50c-4f28-9280-4b81672dd0b3.webp"
    },
    {
        noUrut: 4,
        nama: "AGUNG PURWANTO, S.E.I.",
        dapil: 6,
        partai: "PKB",
        ranked: "EPIC",
        jumlahSuara: 4783,
        jadiGagal: "Gagal",
        basisSuara: "Gedangan",
        suaraDiBasis: 4405,
        kekuatanDiBasis: "92%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha Muda",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/b/0/3/1688660080_451343f0-7b4e-4be8-a21c-0c903c8c2a13.webp"
    },
    {
        noUrut: 5,
        nama: "WISNU PRADONO, S.H.",
        dapil: 6,
        partai: "PDIP",
        ranked: "EPIC",
        jumlahSuara: 4654,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 3502,
        kekuatanDiBasis: "75%",
        statusDiPartai: "transaksional",
        profileSummary: "Ex Wakil fraksi",
        status: "Merah",
        pic: "P Deny & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/1/f/9/1683699353_6fa26a86-08b1-4a10-95b7-145a4921b44b.webp"
    },
    {
        noUrut: 3,
        nama: "TURIDATUS SALIMAH, S.Ag.",
        dapil: 6,
        partai: "PKB",
        ranked: "EPIC",
        jumlahSuara: 4179,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 3746,
        kekuatanDiBasis: "90%",
        statusDiPartai: "Ideologis",
        profileSummary: "Fatayad, Istri PLT Bupati",
        status: "Merah",
        pic: "BPKK & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/1/c/b/1688659054_acfd9651-182f-4e85-9fd6-19043bb76c91.webp"
    },
    {
        noUrut: 1,
        nama: "SISWANTO, S.Sos.",
        dapil: 6,
        partai: "Nasdem",
        ranked: "EPIC",
        jumlahSuara: 4093,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 2783,
        kekuatanDiBasis: "68%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha",
        status: "Hijau",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/9/6/3/1683379392_d6d681f6-31d8-4792-9f4d-63a14468ebf3.webp"
    },
    {
        noUrut: 4,
        nama: "MOHAMMAD SUJAYADI",
        dapil: 6,
        partai: "Gerindra",
        ranked: "RARE",
        jumlahSuara: 2549,
        jadiGagal: "Gagal",
        basisSuara: "Gedangan",
        suaraDiBasis: 2052,
        kekuatanDiBasis: "81%",
        statusDiPartai: "Ideologis",
        profileSummary: "Sekt DPC Gerindra",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/1/a/5/1683778948_055fadbb-78bd-4082-a9ab-eadd3a839c71.webp"
    },
    {
        noUrut: 8,
        nama: "AL HAMZAH",
        dapil: 6,
        partai: "PDIP",
        ranked: "RARE",
        jumlahSuara: 2181,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 1692,
        kekuatanDiBasis: "78%",
        statusDiPartai: "Transaksional",
        profileSummary: "Pengusaha Muda",
        status: "Kuning",
        pic: "BPJE & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/0/7/5/1683699465_e13ffe84-2290-458c-9cea-6545606b1f21.webp"
    },
    {
        noUrut: 2,
        nama: "H. ANGGARA BAGUS WISHNU WARDHANA, S.E.",
        dapil: 6,
        partai: "Gerindra",
        ranked: "COMMON",
        jumlahSuara: 1886,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 988,
        kekuatanDiBasis: "52%",
        statusDiPartai: "?",
        profileSummary: "?",
        status: "Kuning",
        pic: "Tim Hunter",
        photo: ""
    },
    {
        noUrut: 2,
        nama: "SRI OETAMI",
        dapil: 6,
        partai: "PKS",
        ranked: "COMMON",
        jumlahSuara: 1669,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 970,
        kekuatanDiBasis: "58%",
        statusDiPartai: "",
        profileSummary: "",
        status: "Oren",
        pic: "",
        photo: ""
    },
    {
        noUrut: 1,
        nama: "SHOBIKIN, S.Sos., M.M.",
        dapil: 6,
        partai: "PSI",
        ranked: "COMMON",
        jumlahSuara: 1659,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 941,
        kekuatanDiBasis: "57%",
        statusDiPartai: "Transaksional",
        profileSummary: "Kabid Muhammdiyah lamongan",
        status: "Kuning",
        pic: "BPU & Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/8/a/b/1683947291_8cd947f8-91c8-40f2-8469-6be6c662799f.webp"
    },
    {
        noUrut: 2,
        nama: "EMANUEL VICTOR GUNAWAN SOELOWIDJOYO",
        dapil: 6,
        partai: "PSI",
        ranked: "COMMON",
        jumlahSuara: 1484,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 1111,
        kekuatanDiBasis: "75%",
        statusDiPartai: "?",
        profileSummary: "?",
        status: "Merah",
        pic: "Tim Hunter",
        photo: ""
    },
    {
        noUrut: 2,
        nama: "TRI ENDROYONO, S.Pd.",
        dapil: 6,
        partai: "PDIP",
        ranked: "COMMON",
        jumlahSuara: 1476,
        jadiGagal: "Gagal",
        basisSuara: "Gedangan",
        suaraDiBasis: 1032,
        kekuatanDiBasis: "70%",
        statusDiPartai: "Ideologis",
        profileSummary: "Wakil BK PDIP",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/c/7/e/1696247342_5e88747e-0c9b-49e0-887e-6a41ff21b162.webp"
    },
    {
        noUrut: 3,
        nama: "NATALIA KRISTINANINGRUM",
        dapil: 6,
        partai: "PSI",
        ranked: "COMMON",
        jumlahSuara: 1453,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 1063,
        kekuatanDiBasis: "73%",
        statusDiPartai: "?",
        profileSummary: "?",
        status: "Merah",
        pic: "Tim Hunter",
        photo: ""
    },
    {
        noUrut: 1,
        nama: "JONI BASKORO",
        dapil: 6,
        partai: "Demokrat",
        ranked: "COMMON",
        jumlahSuara: 1293,
        jadiGagal: "Gagal",
        basisSuara: "Waru",
        suaraDiBasis: 1096,
        kekuatanDiBasis: "85%",
        statusDiPartai: "Ideologis",
        profileSummary: "Kader",
        status: "Merah",
        pic: "Tim Hunter",
        photo: "https://images.lezen.id/infopemilu.kpu.go.id/a/d/f/1688575372_4cf2a3c3-d0aa-4643-9019-b4f7c343c603.webp"
    }
];